### ISSUE TITLE
Image to Sketch using IP

### ISSUE THREAD

**Issue by bislara** [codezoned/ScriptsDump#245]
Program to turn any image into a pencil sketch using OpenCV of image processing. 

Technology used

- Simple Image Processing Method

**Comment by master-fury** [comment]
Hey @bislara , Please put your scripts into the existing structure. If you think your scripts don't fit any category, then please raise a new issue. Thanks and I'm closing your issue for now.

**Comment by bislara** [comment]
Hey, @master-fury  You had an Image processing structure in your repo. That's the reason I created this issue.  So, I couldn't get the problem? Please describe a little more.

**Comment by bislara** [comment]
Also, I haven't written any script till now. I couldn't get what you mean.

**Comment by bislara** [comment]
@master-fury  Kindly reply to this. and if possible reopen this issue.

**Comment by master-fury** [comment]
Hey @bislara , you misunderstood what I said, this repo has a structure (like machine learning, algo, ds etc. )and whenever you want to add your scripts to them raise a PR so that we can review and merge it. You can mention the issue in your PR template. Creating a new issue every time for a specific script is hard and also it will make things messy. That's why we keep our issues always open. Imagine a situation where we ask the community to drop the scripts related to sorting, we have to create 10+ issues and then check on them, but rather we prefer to create one and let people add more and more and we review it directly. No need to create an issue for specific scripts. Prefer creating an issue for a category. If you still have confusion or doubt, please ask. I'm here to help.

**Comment by bislara** [comment]
Oh, I am really sorry. I follow a little different rule. That's y I did like that. Apologies. 

I will create a PR soon. ✌🤟

**Comment by master-fury** [comment]
Actually, I understand your approach, but that's not possible when you have thousands of scripts. When there is an application dev type project you can create specific issues. Waiting for your PR 😉!
